### ISSUE TITLE
Tag Issue - Fabric 1.19.2

### ISSUE THREAD

**Issue by SpigotDE** [jtorleonstudios/HUB-Awesome-Dungeon-The-End#4]
`[Worker-Main-8/ERROR] Couldn't load tag awesomedungeonend:aws_all_end_structures_avoid as it is missing following references: minecraft:end_city (from Awesome dungeon the end)`

`[Render thread/WARN] Not all defined tags for registry ResourceKey[minecraft:root / minecraft:worldgen/structure_set] are present in data pack: awesomedungeonend:aws_all_end_structures_avoid`

[latest.log](https://gist.github.com/SpigotDE/c559cd692bc9f7b5b8dffe5049a0d940)

**Comment by jtorleonstudios** [comment]
fixed in last version

thanks you

**Comment by SpigotDE** [comment]
Now only this line gets printed:
`[Render thread/INFO]: Structure placement for `awesomedungeonend:aws_all_end_structures/start_pool`: { spacing: 20, separation: 15, salt: 49082056, useValueFromConfiguration: true}`

is this intended ?
[latest.log](https://gist.github.com/SpigotDE/9af6fb0777811be2a27c41be09a2f4b0)
